# -*- coding: utf-8 -*-
"""AP1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Cud1N9BEcd-9ZvIG1UcP6clGHPsCjhM
"""

print("hello")

type('hello')

import random

rand = random.randint(1, 5)

if rand > 3 or rand < 5:
  print("more")

"""jalase 2"""

import random
l = []
counter = 0
while counter < 11 :
  counter += 1
  rand = random.random()
  if rand > 0.5:
    l.append(rand)
  
  else:
    print("less")  
  
print(l)  
print(type(l))
l2 = [1, 2]
l.extend(l2)
print(l)

t = (1, 2, 3, 5)
print(type(t))

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["brand"]

l[:-1]

l3 = [1, 2, 3, 4, 5, 6]
l4 = []
l3.pop(0)

for value in l3:
  l4.append(value * 2)



print(l4)

str1 = 'mehrshad'
list1 = list(str1)
str2 = '!'.join(list1)
print(str2)

#enumerate
for index, value in enumerate(l3):
  l3[index] = 0

#swap
a = 2
b = 3

a, b = b, a

print("a=",a)

"""function definition"""

def say_hello(name):
  return "hello " + name

print(say_hello("mehrshad"))

#getting user input

num = int(input("enter a number: "))
print(num * 2)

class A():
  def __init__(self):
    pass
  def say_hello(self):  
    print("saying hello from A")

class B():
  def __init__(self):
    pass
  def say_hello(self):  
    print("saying hello from B") 

class C(B, A):
  def __init__(self):
    pass

c1 = C()
c1.say_hello()
issubclass(C, B)

#traditional list append
l5 = []
for value in range(0, 10):
  l5.append(value)

print(l5)

#list comprehention

l5 = [value for value in range(0, 10)]
l5[1::2]